name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: cf_coords_test
        environment-file: environment.yaml
        auto-update-conda: false
        auto-activate-base: false
        python-version: '3.12'

    - name: Run tests
      run: |
        conda list
        pytest --continue